name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
        echo "${{secrets.ACTION_PEM_FILE}}" > identity.pem
        chmod 400 identity.pem
        mkdir -p ~/.config/dfx/identity/default
        mv identity.pem ~/.config/dfx/identity/default/identity.pem
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build
      run: |
        cd docusaurus
        npm install
        yarn build
        cd ..
    - name: Deploy
      run: |
        rm canister_ids.json
        dfx start --background --clean
        dfx deploy ic123_frontend --specified-id=gzdkp-wyaaa-aaaan-qd5la-cai --network=ic
        
