name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install DFX
      run: |
        sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
        echo "${{secrets.ACTION_PEM_FILE}}" > identity.pem
        chmod 400 identity.pem
        cat identity.pem
        mkdir -p ~/.config/dfx/identity/default
        mv identity.pem ~/.config/dfx/identity/default/identity.pem
        dfx identity whoami
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build
      run: |
        cd docusaurus
        npm install
        yarn build
        ls
